### ISSUE TITLE
Firefox Focus for iOS creates extraneous changes

### ISSUE THREAD

**Issue by sblatz** [mozilla/firefox-ios-build-tools#40]

**Comment by boek** [comment]
https://github.com/mozilla-l10n/focusios-l10n/pull/40#discussion_r199965116

Delphine pointed out an issue with our latest exports where the path on every `Intro.strings` file is changing which is causing problems. We tried exporting with multiple versions of Xcode and it was the same every time. I also wasn't able to find any changes in the Focus repo that could cause this since the last successful export. So our last idea was maybe something in the script has changed since then.

**Comment by flodolo** [comment]
> So our last idea was maybe something in the script has changed since then.

cc @Delphine

Which script? If it's the one copying strings over to all locales, it simply cannot be. It uses the en-US file as a template, so it's the starting point that includes that change (and it comes out of Xcode via [xcodebuild](https://github.com/mozilla-mobile/ios-l10n-scripts/blob/master/export-locales.sh#L80))
